#!/bin/sh

export MILP_HOME="${MILP_HOME:-$PWD}"

if [ ! -e "$MILP_HOME" ]
then
    echo "$MILP_HOME does not exist" 1>&2
    exit 1
fi

JAR="$MILP_HOME/milp.jar"
CLASS="it.polimi.modaclouds.space4cloud.milp.Main"
if [ ! -e "$JAR" ]
then
    echo "Can't find jarfile to run"
    exit 1
fi

# Deal with Cygwin path issues
cygwin=false
case "`uname`" in
    CYGWIN*) cygwin=true;;
esac
if [ "$cygwin" = "true" ]
then
    JAR=`cygpath -w "$JAR"`
    MILP_HOME=`cygpath -w "$MILP_HOME"`
fi

JVM_ARGS=${JVM_ARGS:--Xmx1200M}

#exec java  $JVM_ARGS -jar "$JAR" "$@"
exec java $JVM_ARGS -cp "$JAR:lib/*" $CLASS "$@"
